### ISSUE TITLE
Clunky string returned from doi_create

### ISSUE THREAD

**Issue by skybristol** [USGS-SDM/usgs_datatools#1]
Great tool for dealing with the stupid not-API situation with the DOIs. Thanks @bserna-usgs for putting this together.

When I create a DOI, I get a string like the following returned from the function:

Created DOI: doi:10.5072/FK24Q7Z41P
doi:10.5072/FK24Q7Z41P

It would be nice to just get the simple DOI string back or else some data structure with additional information if that becomes necessary. With this, I have to parse the string to get out what I want. Workable but kind of a pain.

**Comment by skybristol** [comment]
Oops. Hadn't actually pulled it out yet. So, you are spitting out a message from the function. That's okay but still annoying. Keep it in there if you need, but I find any print out of a function to be a pain in the ass, generally.

**Comment by bserna-usgs** [comment]
Thanks @skybristol! I like the idea of removing the print, the create_doi method will just return the string in the next minor version

**Comment by dignizio-usgs** [comment]
As of most recent version, 'doi_create' function now returns the new DOI's ID.
Example response: _'doi:10.5072/XXXXXXXX'_
