### ISSUE TITLE
'add_primary_doi_manager' fails

### ISSUE THREAD

**Issue by dignizio-usgs** [USGS-SDM/usgs_datatools#13]
ImportError: cannot import name 'add_primary_doi_manager' from 'usgs_datatools.doi' 
(...site-packages\usgs_datatools\doi.py)

I don't see a function called 'add_primary_doi_manager' in the doi.py file. Is it possible the 'USGS DOI Tool Python Module Examples' notebook is out of date?

**Comment by talbertc-usgs** [comment]
Was that function ever in production?  I hadn't used it.  

Just tried updating a manger on an existing record using the existing tools (doi_session.doi_update) and found it to be confusing and a pain:

```
params = doi_session.get_doi('doi:10.5066/F70863HM')
params['users'] = ['talbertc@usgs.gov',
 'sciencebase@ornl.gov',
 'hbattlesmanley@contractor.usgs.gov']
params['date'] = '2017'
params['dateType'] = 'Created'

doi_session.doi_update(params)

```

Wasn't at all clear to me at least or documented anywhere.  If there isn't such a convenience function we should add one.

**Comment by dignizio-usgs** [comment]
Gotcha. Looks like these notebooks were updated as part of the other repo. Function is not present in this codebase.
